// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: type/v1/error.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal.js";

export const protobufPackage = "type.v1";

export const Code = { UNSPECIFIED: "CODE_UNSPECIFIED", FAKE_ERROR: "CODE_FAKE_ERROR" } as const;

export type Code = typeof Code[keyof typeof Code];

export namespace Code {
  export type UNSPECIFIED = typeof Code.UNSPECIFIED;
  export type FAKE_ERROR = typeof Code.FAKE_ERROR;
}

export function codeFromJSON(object: any): Code {
  switch (object) {
    case 0:
    case "CODE_UNSPECIFIED":
      return Code.UNSPECIFIED;
    case 2:
    case "CODE_FAKE_ERROR":
      return Code.FAKE_ERROR;
    default:
      return Code.UNSPECIFIED;
  }
}

export function codeToJSON(object: Code): string {
  switch (object) {
    case Code.UNSPECIFIED:
      return "CODE_UNSPECIFIED";
    case Code.FAKE_ERROR:
      return "CODE_FAKE_ERROR";
    default:
      return "UNSPECIFIED";
  }
}

export function codeToNumber(object: Code): number {
  switch (object) {
    case Code.UNSPECIFIED:
      return 0;
    case Code.FAKE_ERROR:
      return 2;
    default:
      return 0;
  }
}

export interface ErrorMessage {
  code: Code;
  message: string;
}

function createBaseErrorMessage(): ErrorMessage {
  return { code: Code.UNSPECIFIED, message: "" };
}

export const ErrorMessage = {
  encode(message: ErrorMessage, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.code !== Code.UNSPECIFIED) {
      writer.uint32(8).int32(codeToNumber(message.code));
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ErrorMessage {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.code = codeFromJSON(reader.int32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  // encodeTransform encodes a source of message objects.
  // Transform<ErrorMessage, Uint8Array>
  async *encodeTransform(
    source: AsyncIterable<ErrorMessage | ErrorMessage[]> | Iterable<ErrorMessage | ErrorMessage[]>,
  ): AsyncIterable<Uint8Array> {
    for await (const pkt of source) {
      if (globalThis.Array.isArray(pkt)) {
        for (const p of (pkt as any)) {
          yield* [ErrorMessage.encode(p).finish()];
        }
      } else {
        yield* [ErrorMessage.encode(pkt as any).finish()];
      }
    }
  },

  // decodeTransform decodes a source of encoded messages.
  // Transform<Uint8Array, ErrorMessage>
  async *decodeTransform(
    source: AsyncIterable<Uint8Array | Uint8Array[]> | Iterable<Uint8Array | Uint8Array[]>,
  ): AsyncIterable<ErrorMessage> {
    for await (const pkt of source) {
      if (globalThis.Array.isArray(pkt)) {
        for (const p of (pkt as any)) {
          yield* [ErrorMessage.decode(p)];
        }
      } else {
        yield* [ErrorMessage.decode(pkt as any)];
      }
    }
  },

  fromJSON(object: any): ErrorMessage {
    return {
      code: isSet(object.code) ? codeFromJSON(object.code) : Code.UNSPECIFIED,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: ErrorMessage): unknown {
    const obj: any = {};
    if (message.code !== Code.UNSPECIFIED) {
      obj.code = codeToJSON(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ErrorMessage>, I>>(base?: I): ErrorMessage {
    return ErrorMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ErrorMessage>, I>>(object: I): ErrorMessage {
    const message = createBaseErrorMessage();
    message.code = object.code ?? Code.UNSPECIFIED;
    message.message = object.message ?? "";
    return message;
  },
};

export interface DataLoaderOptions {
  cache?: boolean;
}

export interface DataLoaders {
  rpcDataLoaderOptions?: DataLoaderOptions;
  getDataLoader<T>(identifier: string, constructorFn: () => T): T;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
