// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file type/v1/error.proto (package type.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file type/v1/error.proto.
 */
export const file_type_v1_error: GenFile = /*@__PURE__*/
  fileDesc("ChN0eXBlL3YxL2Vycm9yLnByb3RvEgd0eXBlLnYxIjwKDEVycm9yTWVzc2FnZRIbCgRjb2RlGAEgASgOMg0udHlwZS52MS5Db2RlEg8KB21lc3NhZ2UYAiABKAkqMQoEQ29kZRIUChBDT0RFX1VOU1BFQ0lGSUVEEAASEwoPQ09ERV9GQUtFX0VSUk9SEAJCVgoLY29tLnR5cGUudjFCCkVycm9yUHJvdG9QAaICA1RYWKoCB1R5cGUuVjHKAgdUeXBlXFYx4gITVHlwZVxWMVxHUEJNZXRhZGF0YeoCCFR5cGU6OlYxYgZwcm90bzM");

/**
 * @generated from message type.v1.ErrorMessage
 */
export type ErrorMessage = Message<"type.v1.ErrorMessage"> & {
  /**
   * @generated from field: type.v1.Code code = 1;
   */
  code: Code;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message type.v1.ErrorMessage.
 * Use `create(ErrorMessageSchema)` to create a new message.
 */
export const ErrorMessageSchema: GenMessage<ErrorMessage> = /*@__PURE__*/
  messageDesc(file_type_v1_error, 0);

/**
 * @generated from enum type.v1.Code
 */
export enum Code {
  /**
   * @generated from enum value: CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CODE_FAKE_ERROR = 2;
   */
  FAKE_ERROR = 2,
}

/**
 * Describes the enum type.v1.Code.
 */
export const CodeSchema: GenEnum<Code> = /*@__PURE__*/
  enumDesc(file_type_v1_error, 0);

