// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file echo/v1/echo.proto (package echo.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ChatRequest, ChatResponse, EchoRequest, EchoResponse, EchoStreamRequest, EchoStreamResponse, StreamEchoRequest, StreamEchoResponse } from "./echo_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service echo.v1.EchoService
 */
export const EchoService = {
  typeName: "echo.v1.EchoService",
  methods: {
    /**
     * @generated from rpc echo.v1.EchoService.Echo
     */
    echo: {
      name: "Echo",
      I: EchoRequest,
      O: EchoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc echo.v1.EchoService.EchoStream
     */
    echoStream: {
      name: "EchoStream",
      I: EchoStreamRequest,
      O: EchoStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc echo.v1.EchoService.StreamEcho
     */
    streamEcho: {
      name: "StreamEcho",
      I: StreamEchoRequest,
      O: StreamEchoResponse,
      kind: MethodKind.ClientStreaming,
    },
    /**
     * @generated from rpc echo.v1.EchoService.Chat
     */
    chat: {
      name: "Chat",
      I: ChatRequest,
      O: ChatResponse,
      kind: MethodKind.BiDiStreaming,
    },
  }
} as const;

